### ISSUE TITLE
Fatal: <Exception: "ArmorKeywords.esm" requires master "DLCRobot.esm" to be loaded before it.>

### ISSUE THREAD

**Issue by shadedmagus** [TES5Edit/TES5Edit#390]
I am receiving the following message in the log when trying to start FO4Edit with any combination of mods selected:

> Fatal: <Exception: "ArmorKeywords.esm" requires master "DLCRobot.esm" to be loaded before it.>

When the Master/Plugin Selection window is open, I can see that the first ESM files after Fallout4 in the order are "Robot Home Defence.esm" and "ArmorKeywords.esm", and I can see that these are the first two files listed in plugins.txt. But the DLC files, while not in plugins.txt, ARE in the load order - just under these two ESMs.

**Comment by zilav** [comment]
Fixed.

**Comment by Seipherwood** [comment]
Using ProgramVersion 2.3.1.0 and still getting this. Seems ArmorKeywords always loads before DLCRobot.
[00:01:39] (ERROR) Load: "ArmorKeywords.esm" requires master "DLCRobot.esm" to be loaded before it.
