### ISSUE TITLE
[Skyrim] CNAM entries in quest entries need to be case sensitive and are not.

### ISSUE THREAD

**Issue by Arthmoor** [TES5Edit/TES5Edit#469]
For example, tried to change "Blue palace" to "Blue Palace" and while the edit does take, xEdit considers it an ITM when it's not. This needs to be handled like other similar text records so that a change in case isn't treated as an ITM.

Also affects SSE as well if that matters. Possibly other games too.

**Comment by eFrysTon** [comment]
Looking at the source, this should already be fixed... can you check the latest release?

**Comment by Arthmoor** [comment]
If you mean the fresh commits, I'll check that when I get back later The release I have right now still shows those as ITMs.

**Comment by Arthmoor** [comment]
SSEEdit_df8b8a2 still shows the CNAM as an ITM despite the case being different.

https://i.imgur.com/fsvLha8.png

If you need the file, it's in the current beta for USSEP 4.1.4 available on AFK Mods.

**Comment by eFrysTon** [comment]
I'll assume the issue is fixed and close it. Please let me know if you find it's still an issue in the latest release.

**Comment by Arthmoor** [comment]
I have not been able to check because at the time you posted this there was no release to test it with other than trying to compile from source code - which I cannot do.
