### ISSUE TITLE
Expand UTF-8 support to include text fields for translation when -cp:utf-8 is added

### ISSUE THREAD

**Issue by 0xb160c0c5** [TES5Edit/TES5Edit#579]
**What is the version of xEdit you are using?**
SSEEdit 3.3.0 BETA (CF9EFC02) starting session 2018-11-06 19:21:39

**Describe the bug**
xEdit doesn't interpret string encoding in VMAD properties as UTF-8 even -cp:utf-8 is added. Instead, xEdit interpret it as local encoding (For WIn10 Simplified Chinese, it's GBK).

**To Reproduce**
1. Use xTranslator to edit a mod with strings in VMAD properties, replace the strings with Chinese characters.
2. Use xEdit with -cp:utf-8 to open the previous mod.
3. Navigate to the VMAD property.
4. The characters you have just edited in xTranslator become unintelligible.

**Expected behavior**
Treat string encoding in VMAD properties as UTF-8 and properly display.

**Additional context**
Better test using east asian languages (e.g.: Chinese characters, kana or hangul) as the encoding of Latin letters in ASCII and GBK are the same.

**Comment by ElminsterAU** [comment]
Thanks for your report.
The commit referenced above should fix this issue. It is planned to be included in 3.0.1

If you have the time, please drop into the xEdit Discord (just click the Discord button in the top right corner in xEdit), I have an interim version and would welcome it if you could test it. TIA.

**Comment by Sharlikran** [comment]
@0xb160c0c5 @ElminsterAU the OP mentioned this isn't fixed and I tried to get as much actual programming information as I could since I know this isn't as simple as just checking some box and it suddenly works.

One setting was something such as "language for non-unicode programes" in Windows 10 to China(PRC). Just don't blindly change that I don't know if your screen will suddenly look like this or not.

![image](https://user-images.githubusercontent.com/1912426/48242300-676faa80-e38f-11e8-9cb2-f0f9b009b41a.png)

The code page being used is 936 and in Windows 10 they are using WIn10 Simplified Chinese.

![image](https://user-images.githubusercontent.com/1912426/48242619-ee715280-e390-11e8-9333-4383dc37ad75.png)

![image](https://user-images.githubusercontent.com/1912426/48242632-f92be780-e390-11e8-8b3a-012c291354fa.png)

For now I am going to refer the user to issue #501

**Comment by 0xb160c0c5** [comment]
How to reproduce:

1.Keep language in steam as English.
2.Download https://www.nexusmods.com/skyrimspecialedition/mods/1333 , choose "Unofficial Chinese Translation for Skyrim Special Edition (CHS)".
3.Change "Language for non-Unicode programs" to "Chinese(Simplified, PRC)".
4.Open the attachment with SSEEdit, navigate to RRR_SKSE2_Quest "SKSE Quest" [QUST:038682FD]
5.the ModName property displays as "娴嬭瘯鏂囨湰".
6.use xTranslator to open the plugin, enable VMAD edit, find ModName, and it's "测试文本", which is correct.

**Comment by Sharlikran** [comment]
![image](https://user-images.githubusercontent.com/1912426/48242863-ff6e9380-e391-11e8-9464-07b8a29b381c.png)

I see it's the text in the Red box.

**Comment by 0xb160c0c5** [comment]
Change "Language for non-Unicode programs" to "Chinese(Simplified, PRC)" and it will display as “娴嬭瘯鏂囨湰”。
![unknown](https://user-images.githubusercontent.com/26914416/48243102-71d68680-e419-11e8-9a32-ed0f0068a324.png)

**Comment by 0xb160c0c5** [comment]
The UTF8 encoding of "测试文本" is E6 B5 8B AF 95 E6 96 87 E6 9C AC，the GBK encoding of "娴嬭瘯鏂囨湰" is E6 B5 8B AF 95 E6 96 87 E6 9C AC, too.

**Comment by Sharlikran** [comment]
I also found this website: [Webatic](https://www.webatic.com/encoding-explorer)

When I change the encoding in the lower portion to Chinese simplified gb2312 then I get the string that the user does not want.

![image](https://user-images.githubusercontent.com/1912426/48243660-52e2e080-e396-11e8-91a6-c796d449dd26.png)

Change the drop down to Unicode and it's what they want.

![image](https://user-images.githubusercontent.com/1912426/48243673-69893780-e396-11e8-9cda-959e39e0e14b.png)

**Comment by 0xb160c0c5** [comment]
GBK is the superset of GB2312.

**Comment by Sharlikran** [comment]
```
OS info: Windows-10-10.0.17134
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: None; output encoding: None; locale: ('zh_CN', 'cp936')
filesystem encoding: mbcs
```

That was Wrye Bash information but it is what the user has for their system depending on what you need to figure this out in regards to what Delphi needs.

**Comment by Sharlikran** [comment]
Strings in TERM:NAM0, TERM:WNAM RACE:FMRN don't display correctly, because FO4Edit treat their encoding as GBK instead of UTF-8 on Win10 Simplified Chinese.

**To Reproduce**
1.Change "Language for non-Unicode programs" to "Chinese(Simplified, PRC)".
2.Download the attachment in #592 , open it using FO4Edit with -cp:utf-8.
3.Navigate to Terminal, the NAM0 and WNAM become unintelligible.
4.Navigate to Race, the FMRN also become unintelligible.

**Expected behavior**
Take Terminal \ 01004BE8 <TrueStorms_TerminalConfigMain> and Race \ 0104B2D8 <TestHumanRace> as example. TERM:NAM0 should be ""真实的风暴“设置" instead of ""鐪熷疄鐨勯鏆粹€滆缃?", TERM:WNAM should be "选择一项以切换." instead of "閫夋嫨涓€椤逛互鍒囨崲.", the first RACE:FMRN should be "眉毛 - 整体" instead of "鐪夋瘺 - 鏁翠綋".

**Additional context**
This bug only happens on non-localized esps, not on localized esps (such as official esms).
May caused by the code change due to #232 .
[TrueStormsFO4.zip](https://github.com/TES5Edit/TES5Edit/files/2568132/TrueStormsFO4.zip)

@0xb160c0c5 Keep all in one issue please as this is really expanding this functionality.

**Comment by Sharlikran** [comment]
@zilav Do those records usually reference strings files?

**Comment by Sharlikran** [comment]
@MGuffin Same question I had for Zilav.

**Comment by Sharlikran** [comment]
This has been updated enough at this time per these commits

84703d378f1faeed02a17ab20b4505954acadbac

20f425fe78e40010711067c5a8138b1c615a2b83

4115ab237232fa769fee7b0f6b5e94abdb60949d

1a795fb62aeca07dfdc25ba22c7e6cccdba10499

**Comment by WeiWeic6222848** [comment]
same problem on 4.0.1, not working anymore

**Comment by ElminsterAU** [comment]
There is no problem with 4.0.1. Please read and understand the information about codepage support in the What's New document.

**Comment by WeiWeic6222848** [comment]
![image](https://user-images.githubusercontent.com/22558527/52527551-9b2dd980-2cca-11e9-8834-5a1486576d4c.png)
i've readed the what's new document and idk, i guess i changed the general string code page too after that but it still happends.

**Comment by ElminsterAU** [comment]
That's because you set it to utf8, but your file isn't utf8. SSE uses utf8 for every language outside English. TES5, uses different code pages for different languages. As documented in the what's new. Stop trying to set the code page directly and set the correct language instead.

**Comment by WeiWeic6222848** [comment]
ill try, thanks for fast replies! appreciated.

**Comment by Sharlikran** [comment]
@WeiWeic6222848 I have been explaining this a lot. Basically set xEdit to load in the language you actually need. Say English. Then if you have errors, instead of correcting them by trying to start xEdit differently, you need to re-edit/replace the strings with the proper encoding.

The what's new tells you the language and it's code page. 

![image](https://user-images.githubusercontent.com/1912426/52542107-497c6200-2d51-11e9-9c06-4669371bf47f.png)

So if your game runs in English then it will not be in UTF-8 and you have chose the completely worst choice since the official game itself will not load UTF-8 for what you want because the Bethesda EXE will make English code page 1252, which is not UTF-8 at all and they are not the same in any way.

This is what he means bu understanding how things work.

The game supports these code pages natively cp1252, cp1250, cp1251, and cp932 for Japanese
